### ISSUE TITLE
Reporte de practica 4 Equipo Mana

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-de-icp-equipomana#1]
[Reporte de Practica 4 Equipo Mana.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-de-icp-equipomana/files/12811869/Reporte.de.Practica.4.Equipo.Mana.pdf)

**Comment by josealfredo79** [comment]
Falta la calificacion...

**Comment by Edwin14459** [comment]
_Calificación Final:_ **20/20**
**Excelente Trabajo**; Cumple con lo requerido de la rúbrica y los procedimientos echos son entendibles.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
